services:
  db:
    container_name: postgres
    image: postgres:17-alpine3.21
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge   
        
